config/routes.rb
Rails.application.routes.draw do
  root to: 'animals#index'
  resources :animals do
    resources :sightings
  end
  resources :regions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
    render :index
  end

  def new
    @animal = Animal.new
    render :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.sightings.each do |sighting|
      sighting.destroy
    end
    @animal.destroy
    redirect_to animals_path
  end

  private
    def animal_params
      params.require(:animal).permit(:species)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.all
    render :index
  end

  def new
    @region = Region.new
    render :new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to regions_path
    else
      render :new
    end
  end

  def edit
    @region = Region.find(params[:id])
    render :edit
  end

  def show
    @region = Region.find(params[:id])
    render :show
  end

  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      redirect_to regions_path
    else
      render :edit
    end
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end

  private
    def region_params
      params.require(:region).permit(:location)
    end

end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def new
    @animal = Animal.find(params[:animal_id])
    @regions = Region.all
    @sighting = @animal.sightings.new
    render :new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @regions = Region.all
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    render :show
  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @regions = Region.all
    @sighting = Sighting.find(params[:id])
    render :edit
  end

  def update
    @sighting = Sighting.find(params[:id])
    @regions = Region.all
    if @sighting.update(sighting_params)
      redirect_to animal_path(@sighting.animal)
    else
      render :edit
    end
  end

  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@sighting.animal)
  end

  private
  def sighting_params
    params.require(:sighting).permit(:date, :lat, :long, :region)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/edit.html.erb
<h1>Edit animal</h1>

<%= form_for @animal do |f| %>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.submit  %>
<% end %>

app/views/animals/index.html.erb
<h1>Animals</h1>

<% if @animals.any? %>
<ul>
  <% @animals.each do |animal| %>
  <li><%= link_to animal.species, animal_path(animal) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no animals yet.</p>
<% end %>


<p><%= link_to "Create new animal", new_animal_path %></p>
<p><%= link_to "Create new region", new_region_path %></p>
<p><%= link_to "See all regions", regions_path %></p>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= form_for @animal do |f| %>
  <%= f.label :species %>
  <%= f.text_field :species %>
  <%= f.submit  %>
<% end %>

app/views/animals/show.html.erb
<h1><%= @animal.species %></h1>

<% if @animal.sightings.any? %>
  <h4>Here are the sightings for this animal:</h4>

  <% @animal.sightings.each do |sighting| %>
    <ul>
      <li>
        <%= link_to sighting.date, animal_sighting_path(@animal, sighting) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No sightings are listed for this animal.</p>
<% end %>

<p><%= link_to "Add a sighting", new_animal_sighting_path(@animal) %></p>

<p><%= link_to "Edit", edit_animal_path(@animal) %></p>
<p><%= link_to "Delete animal", animal_path(@animal),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to animals", animals_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWildlifeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= link_to "Home", animals_path(@animal) %></p>
    <%= yield %>
  </body>
</html>

app/views/regions/edit.html.erb
<h1>Edit region:</h1>

<%= form_for [@region] do |f| %>
<%= f.label :location %>
<%= f.text_field :location %>
<p><%= f.submit %></p>
<% end %>

app/views/regions/index.html.erb
<h1>Regions</h1>

<% if @regions.any? %>
<ul>
  <% @regions.each do |region| %>
  <li><%= link_to region.location, region_path(region) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no regions yet.</p>
<% end %>


<p><%= link_to "Create new region", new_region_path %></p>

app/views/regions/new.html.erb
<h1>Add a new region:</h1>

<%= form_for [@region] do |f| %>
<%= f.label :location %>
<%= f.text_field :location %>
<p><%= f.submit %></p>
<% end %>

app/views/regions/show.html.erb
<h1><%= @region.location %></h1>

<p><%= link_to "Edit", edit_region_path(@region) %></p>
<p><%= link_to "Delete region", region_path(@region),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to regions", regions_path %></p>

app/views/sightings/edit.html.erb
<h1>Edit sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
<%= f.label :date %>
<%= f.text_field :date %>
<%= f.label :lat %>
<%= f.text_field :lat %>
<%= f.label :long %>
<%= f.text_field :long %>
<%= f.label :region %>
<%= f.select :region, @regions.all.collect {|x| [x.location]}, {} %>
<p><%= f.submit %></p>
<% end %>

app/views/sightings/new.html.erb
<h1>Add a new sighting:</h1>

<%= form_for [@animal, @sighting] do |f| %>
<%= f.label :date %>
<%= f.text_field :date %>
<%= f.label :lat %>
<%= f.text_field :lat %>
<%= f.label :long %>
<%= f.text_field :long %>
<%= f.label :region %>
<%= f.select :region, @regions.all.collect {|x| [x.location]}, {} %>
<p><%= f.submit %></p>
<% end %>

app/views/sightings/show.html.erb
<h1>sighting: <%= @sighting.date %></h1>
<h2>animal: <%= @animal.species %></h2>
<h3><%= @sighting.lat %>, <%= @sighting.long %></h3>
<h4><%= @sighting.region %> </h4>

<p><%= link_to "Edit sighting", edit_animal_sighting_path(@animal, @sighting) %></p>
<p><%= link_to "Delete sighting", animal_sighting_path(@animal, @sighting),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to animal", animal_path(@animal) %></p>